# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.0

    working_directory: ~/boom

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: ./bin/build.sh init

      - run:
          name: Run Tests
          command: |
            pip install pipenv
            pipenv install --dev
            pipenv run mamba

      - store_artifacts:
          path: ./tmp
          destination: test-reports

      - run:
          name: Publish to GemFury
          command: ./bin/build.sh publish

